### ISSUE TITLE
Reorder the setup instructions

### ISSUE THREAD

**Issue by jlaswell** [Realpage/lumen#4]
The setup instructions tell users to run commands on containers before they have run `docker-compose up` or `docker-compose pull`. We need to reorder the steps to preparing the application to account for this.

**Comment by bkuhl** [comment]
It'd also be great to pull those setup instructions into `CONTRIBUTING.md`

**Comment by bkuhl** [comment]
Resolved with https://github.com/Realpage/lumen/pull/11
